# Generated by ChatGPT on 2026-01-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('role', models.CharField(max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('board', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
